services:
  - type: web
    name: backend
    runtime: node
    buildCommand: cd backend && npm install --legacy-peer-deps
    startCommand: cd backend && npm start
    env: production
    envVars:
      - key: PORT
        value: "5000"

  - type: static
    name: frontend
    buildCommand: cd frontend && npm install --legacy-peer-deps && npm run build
    staticPublishPath: frontend/build/client
    envVars:
      - key: VITE_API_URL
        value: https://pm-private-1.onrender.com/api-v1

