services:
  - type: web
    name: backend
    runtime: node
    buildCommand: npm run build
    startCommand: node backend/src/index.js
    env: production
    envVars:
      - key: PORT
        value: "5000"

