services:
  - type: web
    name: backend
    runtime: node
    buildCommand: npm run build
    startCommand: bash -c "cd backend && npm start"
    env: production
    envVars:
      - key: PORT
        value: "5000"

